config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :blue
  get 'level_one' => "blue#level_one"
  get 'level_two' => "blue#level_two"
  get 'level_three' => "blue#level_three"
  get 'level_four' => "blue#level_four"
  get 'level_five' => "blue#level_five"
  get 'level_six' => "blue#level_six"
  get 'level_seven' => "blue#level_seven"

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blue_controller.rb
class BlueController < ApplicationController
  def index
  end
  def level_one
  end
  def level_two
  end
  def level_three
  end
  def level_four
  end
  def level_five
  end
  def level_six
  end
  def level_seven
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:firstname, :lastname, :email, :role)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blue_helper.rb
module BlueHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blue/index.html.erb
<div id="blue-wrapper">

	<div id="heart-img">
		<%= image_tag("blue-heart.png", :alt => "Heart & Dots") %>
	</div> 

	<div id="main-title">
		Everybody Loves Emmy Lou Bug
	</div>

	<div class="lg-grey" id="heart-text">
		…and on this valentines day, you are invited to play a game with…
	</div>
	
	<div id="platto">
		<div id="platto-img">
			<%= image_tag("waving-monsty.png", :alt => "Waving-Monsty") %>
		</div> 
		<div class="lg-grey" id="platto-text">
			...the one and only<br>
			Blue Monsty!
		</div>
	</div>

	<div class="lg-grey" id="end-text">
		Would you like to play?
	</div>

	<div id="menu">
		<div class="face-btn" id="smile">
			<%= link_to level_one_path do %>
				I would<br>
				<i class="fa fa-smile-o fa-4x"></i>
			<% end %>
		</div>
		<div class="face-btn" id="sad">
			I wouldn't<br>
			<i class="fa fa-frown-o fa-4x"></i>
		</div>
	</div>

</div>

app/views/blue/level_five.html.erb
<div id="blue-wrapper">

	<div id="heart-img">
		<%= image_tag("blue-heart.png", :alt => "Heart & Dots") %>
	</div> 

	<div id="main-title">
		Question 3
	</div>

	<div class="center lg-grey" id="heart-text">
		3. I have only one neighbour, we all 
		call her B, I will often start words but rarely finish them you see.
	</div>
	
	<div id="platto">
		<div class="hide" id="platto-img">
			<div id="aa">
				<%= image_tag("Aa.png", :alt => "Aa") %>
			</div> 
		</div> 
		<div class="lg-grey" id="platto-text">

		</div>
	</div>

	<div id="form-wrapper">
		<%= form_tag do %>

	    <%= text_field_tag :answer, "", placeholder: "Enter your answer here!" %>
			<div id="submit-ans">
				Submit Answer
			</div>
			<div class="lg-grey" id="hint">
				HINT
			</div>
		<% end %>
	</div>

	<div class="hide" id="end-text">
		
	</div>

	<div id="menu">
		<%= link_to level_six_path do %>
			<div class="hide center" id="large-btn">
				To the PRIZE :)
			</div>
		<% end %>
	</div>

	<div class="hide" id="correct-monsty">
		<%= image_tag("monsty3.png", :alt => "Correct") %>
	</div>

</div>

<script>

	var mySubmit = document.getElementById("submit-ans");
	var userAnswer = document.getElementById("answer");
	var endText = document.getElementById("end-text");
	var hint = document.getElementById("hint");
	var monsty = document.getElementById("correct-monsty");
	var cont = document.getElementById("large-btn");
	var platto = document.getElementById("platto-img");

	$(document).ready(function() {
		userAnswer.value = "";
	});

	hint.addEventListener("click", function(){
		endText.className = "lg-grey";
		endText.innerHTML = "CHEAT!!! CHEAT!!! The Alphabet!!!"
	});

	mySubmit.addEventListener("click", function(){
		var downAns = userAnswer.value.toLowerCase();
		var correctAns = "a";

		if (downAns.includes(correctAns)) {
			monsty.className = "";	
			cont.className = "center";
			platto.className = ""
			endText.innerHTML = "Scones for Monsty???";
			endText.className = "lg-grey";
		}	
		else {
			userAnswer.value = "";
			endText.innerHTML = "NOB NOB!!! Try Again."
			endText.className = "lg-grey";
		}
	});
	
</script>

app/views/blue/level_four.html.erb
<div id="blue-wrapper">

	<div id="heart-img">
		<%= image_tag("blue-heart.png", :alt => "Heart & Dots") %>
	</div> 

	<div id="main-title">
		Question 2
	</div>

	<div class="center lg-grey" id="heart-text">
		2. I swing both ways, but i’m as straight as they come, I’m also two faced, but i’ll help you all day long!
	</div>
	
	<div id="platto">
		<div class="hide" id="platto-img">
			<div id="door">
				<%= image_tag("door.png", :alt => "Door") %>
			</div> 
		</div> 
		<div class="lg-grey" id="platto-text">

		</div>
	</div>

	<div id="form-wrapper">
		<%= form_tag do %>

	    <%= text_field_tag :answer, "", placeholder: "Enter your answer here!" %>
			<div id="submit-ans">
				Submit Answer
			</div>
			<div class="lg-grey" id="hint">
				HINT
			</div>
		<% end %>
	</div>

	<div class="hide" id="end-text">
		CHEAT!!! One room to the next!
	</div>

	<div id="menu">
		<%= link_to level_five_path do %>
			<div class="hide center" id="large-btn">
				LET'S CONTINUE...
			</div>
		<% end %>
	</div>

	<div class="hide" id="correct-monsty">
		<%= image_tag("monsty2.png", :alt => "Correct") %>
	</div>

</div>

<script>

	var mySubmit = document.getElementById("submit-ans");
	var userAnswer = document.getElementById("answer");
	var endText = document.getElementById("end-text");
	var hint = document.getElementById("hint");
	var monsty = document.getElementById("correct-monsty");
	var cont = document.getElementById("large-btn");
	var platto = document.getElementById("platto-img");

	$(document).ready(function() {
		userAnswer.value = "";
	});

	hint.addEventListener("click", function(){
		endText.className = "lg-grey";
		endText.innerHTML = "CHEAT!!! One room to the next!"
	});

	mySubmit.addEventListener("click", function(){
		var downAns = userAnswer.value.toLowerCase();
		var correctAns = "door";

		if (downAns.includes(correctAns)) {
			monsty.className = "";	
			cont.className = "center";
			platto.className = ""
			endText.innerHTML = "Super Scootin' Yellowbean!";
			endText.className = "lg-grey";
		}	
		else {
			userAnswer.value = "";
			endText.innerHTML = "NOB NOB!!! Try Again."
			endText.className = "lg-grey";
		}
	});
	
</script>

app/views/blue/level_one.html.erb
<div id="blue-wrapper">

	<div id="arms-mosnty-img">
		<%= image_tag("arms-monsty.png", :alt => "arms-monsty") %>
	</div> 
	<div id="heart-img">
		<%= image_tag("blue-heart.png", :alt => "Heart & Dots") %>
	</div> 

	<div id="main-title">
		YIPPIE!
	</div>

	<div class="center lg-grey" id="heart-text">
		You've made Monsty very happy!<br><br>
		On with the game
	</div>
	
	<div id="platto">
		<div id="platto-img">
			<div id="squirrel">
				<%= image_tag("squirrel.png", :alt => "Squirrel") %>
			</div> 
		</div> 
		<div class="lg-grey" id="platto-text">
			...What did the boy squirrel <br>say to the girl squirrel?
		</div>
	</div>

	<div id="tell-me">
		<%= image_tag("tell-me.png", :alt => "Nuts") %>
	</div>

	<div class="hide nuts-img" id="end-text">
		<%= image_tag("nuts.png", :alt => "Nuts") %>
	</div>

	<div id="menu">
		<%= link_to level_two_path do %>
			<div class="hide center" id="large-btn">
				LET'S CONTINUE...
			</div>
		<% end %>
	</div>

</div>

<script>

	document.getElementById("tell-me").addEventListener("click", function(){
		document.getElementById("end-text").className = "nuts-img";
	  document.getElementById("large-btn").className = "center";
	  this.className = "hide"
	});
	
</script>

app/views/blue/level_seven.html.erb
<div id="final-wrapper">

	<div class="red" id="main-title">
		Happy Valentines Day
	</div>

	<div id="finish-img">
		<%= image_tag("final-monsty.png", :alt => "finished-monsty") %>
	</div> 

	<div id="main-title">
		Take a look in Monsty's old wardrobe!
	</div>

</div>

app/views/blue/level_six.html.erb
<div id="blue-wrapper">

	<div id="heart-img">
		<%= image_tag("blue-heart.png", :alt => "Heart & Dots") %>
	</div> 

	<div id="main-title">
		What could it be???
	</div>

	<div class="center lg-grey" id="heart-text">
		So you found the Pan, you got the Door and you revealed the A…<br>
		What could this mean?
	</div>
	
	<div id="platto">
		<div id="platto-img">
			<div id="group">
				<%= image_tag("group.png", :alt => "Aa") %>
			</div> 
		</div> 
		<div class="lg-grey" id="platto-text">

		</div>
	</div>

	<div id="form-wrapper">
		<%= form_tag do %>

	    <%= text_field_tag :answer, "", placeholder: "Enter your answer here!" %>
			<div id="submit-ans">
				Submit Answer
			</div>
			<div class="lg-grey" id="hint">
				HINT
			</div>
		<% end %>
	</div>

	<div class="hide" id="end-text">
	</div>

	<div id="menu">
		<%= link_to level_seven_path do %>
			<div class="hide center" id="large-btn">
				FIND ME!
			</div>
		<% end %>
	</div>

	<div class="hide cake" id="correct-monsty">
		<%= image_tag("celebrate.png", :alt => "Correct") %>
	</div>

</div>

<script>

	var mySubmit = document.getElementById("submit-ans");
	var userAnswer = document.getElementById("answer");
	var endText = document.getElementById("end-text");
	var hint = document.getElementById("hint");
	var monsty = document.getElementById("correct-monsty");
	var cont = document.getElementById("large-btn");
	var platto = document.getElementById("platto-img");

	$(document).ready(function() {
		userAnswer.value = "";
	});

	hint.addEventListener("click", function(){
		endText.className = "lg-grey";
		endText.innerHTML = "Pan --- Door --- A (Say them quickly!)"
	});

	mySubmit.addEventListener("click", function(){
		var downAns = userAnswer.value.toLowerCase();
		var correctAns = "pandora";

		if (downAns.includes(correctAns)) {
			console.log("YEP")
			cont.className = "center";
			endText.innerHTML = ":) YIP YIP YIP YIP YIP YIP YIP!!!";
			endText.className = "lg-grey";
			monsty.className = "cake";
			platto.className = "hide";
		}	
		else {
			console.log("NOPE")
			userAnswer.value = "";
			endText.innerHTML = "NOB NOB!!! Try Again."
			endText.className = "lg-grey";
		}
	});
	
</script>

app/views/blue/level_three.html.erb
<div id="blue-wrapper">

	<div id="heart-img">
		<%= image_tag("blue-heart.png", :alt => "Heart & Dots") %>
	</div> 

	<div id="main-title">
		THE REAL DEAL!
	</div>

	<div class="center lg-grey" id="heart-text">
		1. I’m typically shallow, but I can also be deep, i’m always around, in the kitchen you keep. 
	</div>
	
	<div id="platto">
		<div class="hide" id="platto-img">
			<div id="pan">
				<%= image_tag("pan.png", :alt => "Pan") %>
			</div> 
		</div> 
		<div class="lg-grey" id="platto-text">

		</div>
	</div>

	<div id="form-wrapper">
		<%= form_tag do %>

	    <%= text_field_tag :answer, "", placeholder: "Enter your answer here!" %>
			<div id="submit-ans">
				Submit Answer
			</div>
			<div class="lg-grey" id="hint">
				HINT
			</div>
		<% end %>
	</div>

	<div class="hide" id="end-text">
		CHEAT!!! I usualy have a handle!
	</div>

	<div id="menu">
		<%= link_to level_four_path do %>
			<div class="hide center" id="large-btn">
				LET'S CONTINUE...
			</div>
		<% end %>
	</div>

	<div class="hide" id="correct-monsty">
		<%= image_tag("monsty1.png", :alt => "Correct") %>
	</div>

</div>

<script>

	var mySubmit = document.getElementById("submit-ans");
	var userAnswer = document.getElementById("answer");
	var endText = document.getElementById("end-text");
	var hint = document.getElementById("hint");
	var monsty = document.getElementById("correct-monsty");
	var cont = document.getElementById("large-btn");
	var platto = document.getElementById("platto-img");

	$(document).ready(function() {
		userAnswer.value = "";
	});

	hint.addEventListener("click", function(){
		endText.className = "lg-grey";
		endText.innerHTML = "CHEAT!!! I usualy have a handle!"
	});

	mySubmit.addEventListener("click", function(){
		var downAns = userAnswer.value.toLowerCase();
		var correctAns = "pan";

		if (downAns.includes(correctAns)) {
			monsty.className = "";	
			cont.className = "center";
			platto.className = ""
			endText.innerHTML = "Grander than a goose!";
			endText.className = "lg-grey";
		}	
		else {
			userAnswer.value = "";
			endText.innerHTML = "NOB NOB!!! Try Again."
			endText.className = "lg-grey";
		}
	});
	
</script>

app/views/blue/level_two.html.erb
<div id="blue-wrapper">

	<div id="heart-img">
		<%= image_tag("blue-heart.png", :alt => "Heart & Dots") %>
	</div> 

	<div id="main-title">
		THE WARM UP ROUND!
	</div>

	<div class="center lg-grey" id="heart-text">
		What exists once in a minute, Twice in a moment, But never in a thousand years?
	</div>
	
	<div id="platto">
		<div id="platto-img">
			<div id="clock">
				<%= image_tag("clock.png", :alt => "Clock") %>
			</div> 
		</div> 
		<div class="lg-grey" id="platto-text">

		</div>
	</div>

	<div id="form-wrapper">
		<%= form_tag do %>

	    <%= text_field_tag :answer, "", placeholder: "Enter your answer here!" %>
			<div id="submit-ans">
				Submit Answer
			</div>
			<div class="lg-grey" id="hint">
				HINT
			</div>
		<% end %>
	</div>

	<div class="hide" id="end-text">
	</div>

	<div id="menu">
		<%= link_to level_three_path do %>
			<div class="hide center" id="large-btn">
				LET'S CONTINUE...
			</div>
		<% end %>
	</div>

	<div class="hide" id="correct-monsty">
		<%= image_tag("correct1.png", :alt => "Correct") %>
	</div>

</div>

<script>

	var mySubmit = document.getElementById("submit-ans");
	var userAnswer = document.getElementById("answer");
	var endText = document.getElementById("end-text");
	var hint = document.getElementById("hint");
	var monsty = document.getElementById("correct-monsty");
	var cont = document.getElementById("large-btn");

	$(document).ready(function() {
		userAnswer.value = "";
	});

	hint.addEventListener("click", function(){
		endText.className = "lg-grey";
		endText.innerHTML = "CHEAT!!! It's a single letter!"
	});

	mySubmit.addEventListener("click", function(){
		var downAns = userAnswer.value.toLowerCase();
		var correctAns = "m";

		if (downAns.includes(correctAns)) {
			monsty.className = "";	
			cont.className = "center";
			endText.innerHTML = "Scootberry farm on a Sunday!";
			endText.className = "lg-grey";
		}	
		else {
			userAnswer.value = "";
			endText.innerHTML = "NOB NOB!!! Try Again."
			endText.className = "lg-grey";
		}
	});
	
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jugglejob</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :role %><br>
    <%= f.text_field :role %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<div id="landing-wrapper">
	
	<div class="center" id="main-logo">
		Jugglejob<small>.com</small>
	</div>
	<div class="center" id="welcome-heading">
		Connecting trades & customers
	</div>
	<div class="center sub-heading" id="upper-sub-heading">
		Looking after your own couldn’t be easier.
	</div>
	<div class="" id="white-banner">
		<div class="row" id="builder-image-row">
			<div class="col-md-12" id="builder-image"><%= image_tag("builders.png", :alt => "builders")%></div>
		</div>
	</div>
	<div class="center sub-heading" id="lower-sub-heading">
		Track your project from enquiry to completion.
	</div>
	<div class="row" id="circle-stats">
		<div class="col-sm-1"></div>
		<div class="center col-sm-2 reduced-padding">
			<div class="landing-circle-header">
				Enquiry
			</div> 
			<div class="landing-stat-circle">
				<i class="icon-note icon" title="Job at enquiry stage"></i>
			</div>
			<div class="landing-circle-text">
				Submit an enquiry to your prefered tradesmen. Let them know what you want.
			</div> 
		</div>
		<div class="center col-sm-2 reduced-padding">
			<div class="landing-circle-header">
				Quoting
			</div> 
			<div class="landing-stat-circle">
				<i class="icon-calculator icon" title="A quote is being compiled"></i>
			</div>
			<div class="landing-circle-text">
				Get updated during the quoting process and access your final quote.
			</div> 
		</div>
		<div class="center col-sm-2 reduced-padding">
			<div class="landing-circle-header">
				Booking
			</div> 
			<div class="landing-stat-circle">
				<i class="icon-calendar icon" title="Quote has been accepted and a date for work has been booked"></i>
			</div>
			<div class="landing-circle-text">
				Get a confirmed start date, and be notified if anything changes.
			</div> 
		</div>
		<div class="center col-sm-2 reduced-padding">
			<div class="landing-circle-header">
				Start
			</div> 
			<div class="landing-stat-circle">
				<i class="icon-rocket icon" title="Job is currently active and work is underway"></i>
			</div>
			<div class="landing-circle-text">
				Keep track of changes, invoices, updates, and more.
			</div> 
		</div>
		<div class="center col-sm-2 reduced-padding">
			<div class="landing-circle-header">
				Complete
			</div> 
			<div class="landing-stat-circle">
				<i class="icon-check icon" title="Work has been completed"></i>
			</div>
			<div class="landing-circle-text">
				Leave feedback, <br>Recieve a final invoice. <br>Sign the job off.
			</div> 
		</div>
		<div class="col-sm-1"></div>
	</div>

	<div id="large-white-banner">
		<div class="row shots-row">
			<div class="center col-sm-12"><%= image_tag("overlap-shots.png", :alt => "builders")%></div>
		</div>
		<div class="center sub-heading" id="features-sub-heading">
			Key features.
		</div>
		<div id="features-list">
			<ul>
				<li>Invite trades you employ to use Jugglejob to enjoy the full benefits.</li>
				<li>Make enquires to any registered trade, Jugglejob will guide you through the process.</li>
				<li>Recieve updates from your contractor through email alerts and through your own personal job dashboard.</li>
				<li>Keep track of balances and job durations, start dates, extras, and more.</li>
				<li>Rate your trade, and keep them stored as a prefered contractor for next time.</li>
			</ul>
		</div>

	</div>

	<div class="center sub-heading" id="coming-soon-sub-heading">
		Coming Soon!
	</div>
	<div class="center" id="copyright"><i class="fa fa-copyright"></i> 2016-2017</div>

</div>